test con formatos
PabloLarrie/HsDecker pull request #2
Opened 2021-02-11 20:34 UTC by PabloLarrie

Mira a ver si no está muy mal... Los test funcionan todos. No sé si es todo lo que querías...

2021-02-12 09:59 UTC, aitorbouzas requested changes
No estoy muy seguro de que un mazo por defecto tenga standard = false. Quizás el default sería standard = true por dos motivos:
1. Si estás creando cartas nuevas, probablemente sean de standard
2. Los mazos más creados, son los de standard

2021-02-12 09:59 UTC, aitorbouzas commented on conftest.py
> +    pri2 = CardFactory(standard = False)
Las variables de este tipo no son muy explícitas. Mejor llamarlas por lo que son `card_priest` en este caso. ¿Por qué 2 si es la única?

2021-02-12 09:59 UTC, aitorbouzas commented on decks/tests/test_models.py
> +        DeckCard(deck=deck_priest, card=card_priest, quantity=1, golden=True).save()
Los tests por lo normal comprueban si dan error, no es necesario que compruebes que no da error. Esto no está mal, pero tampoco es 100% necesario porque si hay un problema debería dar error en los otros tests.

2021-02-12 10:14 UTC, PabloLarrie commented on conftest.py
> +    pri2 = CardFactory(standard = False)
Es que hay card_priest y card_priest_savage, porque sino me hago un lío. Al principio metí una clase nueva, mage, pero me daba error porque necesitaba dos decks y dos cartas de la misma clase.

2021-02-12 10:15 UTC, PabloLarrie commented on decks/tests/test_models.py
> +        DeckCard(deck=deck_priest, card=card_priest, quantity=1, golden=True).save()
Mayb. Como hay 4 posibilidades: carta St en mazo St, carta St en mazo Sv, carta Sv en mazo St, y carta Sv en mazo Sv, compruebo que todo funcione. (St = standard, Sv = savage)

2021-02-12 10:24 UTC, aitorbouzas commented on conftest.py
> +    pri2 = CardFactory(standard = False)
Igualmente no tiene sentido que le llamas `pri2`. Dentro del scope de este método no hay conflicto si le llamas otra vez `card_priest`. Siempre es mejor que los nombres de las variables sean explícitas y auto explicativas.

2021-02-15 15:09 UTC, aitorbouzas commented
Haz un update con lo que te dije del nombre de la variable, luego puedes hacer merge.

2021-02-16 15:46 UTC, merged